Repository Dev-FE-3/toy-project2-team1, pull requests merged in 2025-03, with the labels that each got.

#14 feat: 급여명세서 기능 구현
  public/images/icon-chevron-left.svg
  public/images/icon-chevron-right.svg
  public/images/no-data.svg
  src/features/design-guide/CalendarModalGuide.jsx
  src/features/design-guide/DesignGuide.jsx
  src/features/pay-stub/PayStub.jsx
  src/features/pay-stub/components/Header.jsx
  src/features/pay-stub/components/Notification.jsx
  src/features/pay-stub/components/PayDetail.jsx
  src/features/pay-stub/components/Summary.jsx
  src/features/pay-stub/components/components.jsx
  src/features/pay-stub/hooks/useFetchPayStub.js
  src/features/pay-stub/store.js
  src/features/pay-stub/utils/payStubSummary.js
  src/shared/components/calendar/CalendarModal.jsx
  src/shared/components/contemt-wrap/ContentWrap.jsx
  src/shared/components/content-wrap/ContentWrap.jsx
  src/shared/components/loading-spinner/LoadingSpinner.jsx
  src/shared/components/modal/Modal.jsx
Labels: ✨ feat

#20 style: 테이블 스타일 수정
  src/features/admin/approval/Approval.jsx
  src/features/admin/approval/TableCommonStyles.js
  src/features/admin/approval/components/Table.jsx
  src/features/admin/approval/components/TableHeader.jsx
  src/features/admin/approval/components/TableRow.jsx
  src/features/my-document/MyDocument.jsx
  src/features/my-document/components/Table.jsx
Labels: 💄 style

#25 feat: PayStub 리덕스로 상태관리
  src/features/pay-stub/PayStub.jsx
  src/features/pay-stub/components/Header.jsx
  src/features/pay-stub/components/PayDetail.jsx
  src/features/pay-stub/components/Summary.jsx
  src/features/pay-stub/hooks/useFetchPayStub.js
  src/shared/redux/reducer/userPayStubSlice.js
  src/shared/redux/store/index.ts
Labels: 🔨 refactor

#39 fix: Timestamp 비직렬화 문제 해결, utils 함수 통합, import 경로의 대소문자 수정
  src/features/admin/approval/Approval.jsx
  src/features/admin/approval/api/GetPayrollCorrections.js
  src/features/admin/approval/components/Table.jsx
  src/features/admin/approval/components/TableRow.jsx
  src/features/admin/pay-stub/PayStub.jsx
  src/features/design-guide/CalendarModalGuide.jsx
  src/features/home/components/DocumentList.jsx
  src/features/my-document/MyDocument.jsx
  src/features/my-document/components/Table.jsx
  src/features/my-document/components/TableRow.jsx
  src/features/pay-stub/PayStub.jsx
  src/shared/components/calendar/CalendarModal.jsx
  src/shared/utils/date.js
  src/shared/utils/dateUtils.js
Labels: 🐛 fix

#46 fix: TableRow.jsx파일 import 경로 대소문자 수정
  src/features/admin/approval/components/TableRow.jsx
Labels: 🐛 fix

#49 fix: 비동기 작업이 완료된 후 데이터 렌더링 하도록 수정
  src/features/admin/approval/components/TableRow.jsx
Labels: 🐛 fix

#43 refactor: 디자인 통일화 작업
  public/images/icon-caution.svg
  src/features/admin/approval/Approval.jsx
  src/features/admin/approval/TableCommonStyles.js
  src/features/admin/pay-stub/PayStub.jsx
  src/features/admin/pay-stub/components/PayStubTable.jsx
  src/features/home/components/EmployeeInfo.jsx
  src/features/login/Login.jsx
  src/features/login/components/LoginError.jsx
  src/features/my-document/MyDocument.jsx
  src/features/work-schedule/WorkSchedule.jsx
  src/features/work-schedule/components/Calendar.jsx
  src/features/work-schedule/components/CalendarHeader.jsx
  src/features/work-schedule/components/DayCell.jsx
  src/shared/components/contemt-wrap/ContentWrap.jsx
  src/shared/components/content-wrap/ContentWrap.jsx
  src/shared/components/modal/Modal.jsx
  src/shared/components/modal/Notification.jsx
  src/shared/components/pagination/Pagination.jsx
Labels: 💄 style, 🔨 refactor

#51 fix: 모달 상태 관리 & 불필요한 console.log 삭제
  src/features/admin/pay-stub/PayStub.jsx
  src/features/admin/pay-stub/api/copyAndInsertPayrollData.js
  src/features/admin/pay-stub/api/getCollectionWithFilter.js
  src/features/login/Login.jsx
  src/features/login/api/loginAuth.js
  src/features/work-schedule/components/AddEventModal.jsx
  src/shared/api/firebase/fetchUserData.js
  src/shared/api/firebase/fetchWorkSchedule.js
  src/shared/api/firebase/firestore.js
  src/shared/components/sideMenu/SideMenu.jsx
Labels: 🐛 fix

#50 fix: 홈 문서리스트 날짜 NaN 오류 수정
  src/features/home/components/CheckList.jsx
  src/features/home/components/DocumentList.jsx
Labels: 🐛 fix

#52 fix: 내급여 페이지 오류 수정
  src/features/pay-stub/components/Header.jsx
  src/features/pay-stub/components/Notification.jsx
Labels: 🐛 fix

#54 feat: 페이지네이션 컴포넌트에 trottle 딜레이 변경
  src/shared/components/pagination/Pagination.jsx
Labels: 🔨 refactor

#55 style: 일정 등록 모달의 라벨 색상 변경
  src/features/work-schedule/components/AddEventModal.jsx
Labels: 🔨 refactor

#58 docs: README 최종
  README.md
Labels: 📝 docs
